version: '3'

services:
  bitwarden:
    image: bitwardenrs/server:latest
    restart: unless-stopped
    volumes:
      - ./data:/data
    environment:
      - DOMAIN=${URL:?}
      - WEBSOCKET_ENABLED=${WS_ENABLE:?}
      - SIGNUPS_ALLOWED=${SIGN_UP:?}
      - ADMIN_TOKEN=${ADMIN_TOKEN:?}
    ports:
      - 8084:80 # HTTP traffic
      - 3012:3012 # websocket traffic
