services:
  plex:
    runtime: nvidia
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - VERSION=docker
    volumes:
      - ./plex_config:/config
      - /path/to/tv:/tv
      - /path/to/movies:/movies
      - /path/to/music:/music
    restart: unless-stopped