version: "3.5"

services:
  photoprism:
    image: photoprism/photoprism:latest
    depends_on:
      - mariadb
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    ports:
      - "2342:2342"
    environment:
      - PHOTOPRISM_ADMIN_USER=${ADMIN_USER:?}
      - PHOTOPRISM_ADMIN_PASSWORD=${ADMIN_PASSWORD:?}
      - PHOTOPRISM_AUTH_MODE=${AUTH_MODE:?}
      - PHOTOPRISM_SITE_URL=${SITE_URL:?} # server URL in the format "http(s)://domain.name(:port)/(path)"
      - PHOTOPRISM_ORIGINALS_LIMIT=${MAX_FILE_SIZE:?}
      - PHOTOPRISM_HTTP_COMPRESSION=${COMPRESSION:?}
      - PHOTOPRISM_LOG_LEVEL=${LOG_LEVEL:?}
      - PHOTOPRISM_READONLY=${READ_ONLY:?}
      - PHOTOPRISM_EXPERIMENTAL=${EXPERIMENTAL:?} # enables experimental features
      - PHOTOPRISM_DISABLE_CHOWN=${DISABLE_CHOWN:?} # disables updating storage permissions via chmod and chown on startup
      - PHOTOPRISM_DISABLE_WEBDAV=${DISABLE_WEBDAV:?} # disables built-in WebDAV server
      - PHOTOPRISM_DISABLE_SETTINGS=${DISABLE_SETTINGS:?} # disables settings UI and API
      - PHOTOPRISM_DISABLE_TENSORFLOW=${DISABLE_TENSORFLOW:?} # disables all features depending on TensorFlow
      - PPHOTOPRISM_DISABLE_FACES=${DISABLE_FACES:?} # disables face detection and recognition (requires TensorFlow)
      - PHOTOPRISM_DISABLE_CLASSIFICATION=${DISABLE_CLASSIFICATION:?} # disables image classification (requires TensorFlow)
      - PHOTOPRISM_DISABLE_RAW=${DISABLE_RAW:?} # disables indexing and conversion of RAW files
      - PHOTOPRISM_RAW_PRESETS=${DISABLE_RAW_PRESETS:?} # enables applying user presets when converting RAW files (reduces performance)
      - PHOTOPRISM_JPEG_QUALITY=${JPG_QUALITY:?}
      - PHOTOPRISM_DETECT_NSFW=${DETECT_NSFW:?} # automatically flags photos as private that MAY be offensive (requires TensorFlow)
      - PHOTOPRISM_UPLOAD_NSFW=${DETECT_NSFW:?} # allows uploads that MAY be offensive (no effect without TensorFlow)
      - PHOTOPRISM_DATABASE_DRIVER=mysql # use MariaDB 10.5+ or MySQL 8+ instead of SQLite for improved performance
      - PHOTOPRISM_DATABASE_SERVER=${DATABASE_SERVER:?} # MariaDB or MySQL database server (hostname:port)
      - PHOTOPRISM_DATABASE_NAME=${DB_NAME:?}
      - PHOTOPRISM_DATABASE_USER=${DB_USER:?}
      - PHOTOPRISM_DATABASE_PASSWORD=${DB_PASSWORD:?}
      - PHOTOPRISM_SITE_DESCRIPTION=${SITE_DESCRIPTION:?}
      - PHOTOPRISM_SITE_AUTHOR=${SITE_AUTHOR:?}
      - PHOTOPRISM_SITE_CAPTION=${SITE_CAPTION:?}
      - PHOTOPRISM_INIT=${INIT:?}
      - PHOTOPRISM_FFMPEG_ENCODER=${FFMPEG_ENCODER:?}
      - PHOTOPRISM_FFMPEG_BITRATE=${FFMPEG_BITRATE:?}
      - NVIDIA_VISIBLE_DEVICES=all
      # - NVIDIA_DRIVER_CAPABILITIES="compute,video,utility"
      - PHOTOPRISM_GID=1000
      - PHOTOPRISM_UMASK=0
    user: "1000:1000"
    working_dir: "/photoprism" # do not change or remove
    volumes:
      - "./photos:/photoprism/originals" # Original media files (DO NOT REMOVE)
      - "./storage:/photoprism/storage" # *Writable* storage folder for cache, database, and sidecar files (DO NOT REMOVE)
    deploy:
      resources:
        reservations:
          devices:
            - driver: "nvidia"
              count: 1
              capabilities: [ gpu ]

  mariadb:
    restart: unless-stopped
    image: mariadb:10.9
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    command: mysqld --innodb-buffer-pool-size=512M --transaction-isolation=READ-COMMITTED --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=512 --innodb-rollback-on-timeout=OFF --innodb-lock-wait-timeout=120
    volumes:
      - "./db:/var/lib/mysql" # DO NOT REMOVE
    environment:
      - MARIADB_AUTO_UPGRADE=1
      - MARIADB_INITDB_SKIP_TZINFO=1
      - MARIADB_DATABASE=${DB_NAME:?}
      - MARIADB_USER=${DB_USER:?}
      - MARIADB_PASSWORD=${DB_PASSWORD:?}
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD:?}
