services:
  wordpressdb:
    container_name: dbwordpressdb
    image: mariadb:10.5
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:?}
      MYSQL_USER: ${DB_USER:?}
      MYSQL_PASSWORD: ${DB_PASSWORD:?}
      MYSQL_DATABASE: ${DB_NAME:?}

  wordpress:
    depends_on:
      - wordpressdb
    image: wordpress:latest
    ports:
      - "8000:80"
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: wordpressdb:3306
      WORDPRESS_DB_USER: ${DB_USER:?}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD:?}
      WORDPRESS_DB_NAME: ${DB_NAME:?}
      WORDPRESS_ADMIN_USER: ${WP_ADMIN_USER:?}
      WORDPRESS_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD:?}
    volumes:
      - ./data:/var/www/html
      - ./opcache.ini:/usr/local/etc/php/conf.d/opcache.ini
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
