services:
  jellyfin:
    runtime: nvidia
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./jellyfin_config:/config
      - /path/to/tvshows:/data/tvshows
      - /path/to/movies:/data/movies
      - /path/to/music:/data/music
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped